[build]
pre-build = ["apt-get install -y protobuf-compiler"]

[target.aarch64-unknown-linux-gnu]
pre-build = ["apt-get install -y protobuf-compiler"]

[target.armv7-unknown-linux-gnueabihf.env]
volumes = [
    "BUILD_DIR",
]
