[target.armv7-unknown-linux-gnueabihf.env]
volumes = [
    "BUILD_DIR",
]

[target.x86_64-unknown-linux-gnu]
dockerfile = "./.github/cross-docker/Dockerfile-cross-debian-11"
pre-build = ["apt-get install -y libtss2-dev llvm-dev libclang-dev clang"]
