[env]
CROSS_TARGET = "${CARGO_MAKE_PROFILE}"
FEATURES = "ecc608"
BUILD_COMMAND = "cross"

[env.x86_64-tpm-debian-gnu]
CROSS_TARGET = "x86_64-unknown-linux-gnu"
CROSS_BUILD_DOCKERFILE = "./.github/cross-docker/Dockerfile-cross-debian-11"
FEATURES = "tpm"

[tasks.build]
description = "Runs the cross/cargo rust compiler."
category = "Build"
install_crate = false
condition = { env_set = ["CROSS_TARGET", "BUILD_COMMAND", "CROSS_BUILD_DOCKERFILE"] }
command = "${BUILD_COMMAND}"
args = [
  "build",
  "--target",
  "${CROSS_TARGET}",
  "--features",
  "${FEATURES}",
  "--release"
]


