[target.mipsel-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-args=-static",
]

[target.x86_64-unknown-linux-gnu.env]
passthrough = [
    "CPLUS_INCLUDE_PATH",
    "LIBCLANG_PATH",
]

[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "CPLUS_INCLUDE_PATH",
    "LIBCLANG_PATH",
]

